### ISSUE TITLE
Alacritty support

### ISSUE THREAD

**Issue by ston1x** [jeffkreeftmeijer/appsignal.terminal#3]
It would be nice to add support for Alacritty:
https://github.com/alacritty/alacritty/wiki/Color-schemes

The colors which Alacritty uses are in `'0x{hex color code}'` format

**Comment by jeffkreeftmeijer** [comment]
As per https://github.com/jeffkreeftmeijer/appsignal.terminal/pull/4#issuecomment-752413778; I’d love to see a separate project for an Alacritty color scheme! 👍
